#!/bin/bash

if [ "$#" -ge 1 ]
then
  docker run \
    -d \
    -it \
    -e MYSQL_ROOT_PASSWORD=$1 \
    -p 3306:3306 \
    -p 33060:33060 \
    --restart unless-stopped \
    --name devel-mysql \
    devel-mysql:1.0
else
  echo "ERROR: no argument detected"
  echo "./devel-run <mysql_password>"
fi
